export type AirportRegion = 'northeast' | 'southeast' | 'midwest' | 'south' | 'mountain' | 'west'

export interface Airport {
  code: string
  city: string
  name: string
  region: AirportRegion
}

export const US_AIRPORTS: Airport[] = [
  { code: 'ATL', city: 'Atlanta, GA',            name: 'Hartsfield-Jackson Atlanta International',    region: 'southeast' },
  { code: 'LAX', city: 'Los Angeles, CA',         name: 'Los Angeles International',                   region: 'west' },
  { code: 'ORD', city: 'Chicago, IL',             name: "O'Hare International",                        region: 'midwest' },
  { code: 'DFW', city: 'Dallas/Fort Worth, TX',   name: 'Dallas/Fort Worth International',             region: 'south' },
  { code: 'DEN', city: 'Denver, CO',              name: 'Denver International',                        region: 'mountain' },
  { code: 'JFK', city: 'New York, NY',            name: 'John F. Kennedy International',               region: 'northeast' },
  { code: 'LAS', city: 'Las Vegas, NV',           name: 'Harry Reid International',                    region: 'west' },
  { code: 'MCO', city: 'Orlando, FL',             name: 'Orlando International',                       region: 'southeast' },
  { code: 'CLT', city: 'Charlotte, NC',           name: 'Charlotte Douglas International',             region: 'southeast' },
  { code: 'SEA', city: 'Seattle, WA',             name: 'Seattle-Tacoma International',                region: 'west' },
  { code: 'PHX', city: 'Phoenix, AZ',             name: 'Phoenix Sky Harbor International',            region: 'mountain' },
  { code: 'IAH', city: 'Houston, TX',             name: 'George Bush Intercontinental',                region: 'south' },
  { code: 'MIA', city: 'Miami, FL',               name: 'Miami International',                         region: 'southeast' },
  { code: 'BOS', city: 'Boston, MA',              name: 'Logan International',                         region: 'northeast' },
  { code: 'EWR', city: 'Newark, NJ',              name: 'Newark Liberty International',                region: 'northeast' },
  { code: 'MSP', city: 'Minneapolis, MN',         name: 'Minneapolis-Saint Paul International',        region: 'midwest' },
  { code: 'DTW', city: 'Detroit, MI',             name: 'Detroit Metropolitan Wayne County',           region: 'midwest' },
  { code: 'PHL', city: 'Philadelphia, PA',        name: 'Philadelphia International',                  region: 'northeast' },
  { code: 'LGA', city: 'New York, NY',            name: 'LaGuardia Airport',                           region: 'northeast' },
  { code: 'FLL', city: 'Fort Lauderdale, FL',     name: 'Fort Lauderdale-Hollywood International',     region: 'southeast' },
  { code: 'BWI', city: 'Baltimore, MD',           name: 'Baltimore/Washington International',          region: 'northeast' },
  { code: 'IAD', city: 'Washington, DC',          name: 'Dulles International',                        region: 'northeast' },
  { code: 'DCA', city: 'Washington, DC',          name: 'Ronald Reagan Washington National',           region: 'northeast' },
  { code: 'MDW', city: 'Chicago, IL',             name: 'Chicago Midway International',                region: 'midwest' },
  { code: 'SFO', city: 'San Francisco, CA',       name: 'San Francisco International',                 region: 'west' },
  { code: 'HNL', city: 'Honolulu, HI',            name: 'Daniel K. Inouye International',              region: 'west' },
  { code: 'SAN', city: 'San Diego, CA',           name: 'San Diego International',                     region: 'west' },
  { code: 'PDX', city: 'Portland, OR',            name: 'Portland International',                      region: 'west' },
  { code: 'STL', city: 'St. Louis, MO',           name: 'St. Louis Lambert International',             region: 'midwest' },
  { code: 'TPA', city: 'Tampa, FL',               name: 'Tampa International',                         region: 'southeast' },
  { code: 'OAK', city: 'Oakland, CA',             name: 'Oakland International',                       region: 'west' },
  { code: 'HOU', city: 'Houston, TX',             name: 'William P. Hobby Airport',                    region: 'south' },
  { code: 'MCI', city: 'Kansas City, MO',         name: 'Kansas City International',                   region: 'midwest' },
  { code: 'CLE', city: 'Cleveland, OH',           name: 'Cleveland Hopkins International',             region: 'midwest' },
  { code: 'SLC', city: 'Salt Lake City, UT',      name: 'Salt Lake City International',                region: 'mountain' },
  { code: 'RDU', city: 'Raleigh-Durham, NC',      name: 'Raleigh-Durham International',                region: 'southeast' },
  { code: 'AUS', city: 'Austin, TX',              name: 'Austin-Bergstrom International',              region: 'south' },
  { code: 'BNA', city: 'Nashville, TN',           name: 'Nashville International',                     region: 'southeast' },
  { code: 'SMF', city: 'Sacramento, CA',          name: 'Sacramento International',                    region: 'west' },
  { code: 'MKE', city: 'Milwaukee, WI',           name: 'General Mitchell International',              region: 'midwest' },
  { code: 'ABQ', city: 'Albuquerque, NM',         name: 'Albuquerque International Sunport',           region: 'mountain' },
  { code: 'BDL', city: 'Hartford, CT',            name: 'Bradley International',                       region: 'northeast' },
  { code: 'BUF', city: 'Buffalo, NY',             name: 'Buffalo Niagara International',               region: 'northeast' },
  { code: 'MSY', city: 'New Orleans, LA',         name: 'Louis Armstrong New Orleans International',   region: 'south' },
  { code: 'JAX', city: 'Jacksonville, FL',        name: 'Jacksonville International',                  region: 'southeast' },
  { code: 'CHS', city: 'Charleston, SC',          name: 'Charleston International',                    region: 'southeast' },
  { code: 'SAT', city: 'San Antonio, TX',         name: 'San Antonio International',                   region: 'south' },
  { code: 'OGG', city: 'Maui, HI',               name: 'Kahului Airport',                             region: 'west' },
  { code: 'KOA', city: 'Kona, HI',               name: 'Kona International',                          region: 'west' },
  { code: 'IND', city: 'Indianapolis, IN',        name: 'Indianapolis International',                  region: 'midwest' },
  { code: 'CMH', city: 'Columbus, OH',            name: 'John Glenn Columbus International',           region: 'midwest' },
  { code: 'PIT', city: 'Pittsburgh, PA',          name: 'Pittsburgh International',                    region: 'northeast' },
  { code: 'RSW', city: 'Fort Myers, FL',          name: 'Southwest Florida International',             region: 'southeast' },
  { code: 'PBI', city: 'West Palm Beach, FL',     name: 'Palm Beach International',                    region: 'southeast' },
  { code: 'BOI', city: 'Boise, ID',               name: 'Boise Airport',                               region: 'mountain' },
  { code: 'OKC', city: 'Oklahoma City, OK',       name: 'Will Rogers World Airport',                   region: 'south' },
  { code: 'TUL', city: 'Tulsa, OK',               name: 'Tulsa International',                         region: 'south' },
  { code: 'ELP', city: 'El Paso, TX',             name: 'El Paso International',                       region: 'mountain' },
  { code: 'ALB', city: 'Albany, NY',              name: 'Albany International',                        region: 'northeast' },
  { code: 'RIC', city: 'Richmond, VA',            name: 'Richmond International',                      region: 'northeast' },
  { code: 'GRR', city: 'Grand Rapids, MI',        name: 'Gerald R. Ford International',                region: 'midwest' },
  { code: 'CVG', city: 'Cincinnati, OH',          name: 'Cincinnati/Northern Kentucky International',  region: 'midwest' },
  { code: 'SNA', city: 'Orange County, CA',       name: 'John Wayne Airport',                          region: 'west' },
  { code: 'SJC', city: 'San Jose, CA',            name: 'Norman Y. Mineta San José International',     region: 'west' },
  { code: 'BHM', city: 'Birmingham, AL',          name: 'Birmingham-Shuttlesworth International',      region: 'southeast' },
  { code: 'SJU', city: 'San Juan, PR',            name: 'Luis Muñoz Marín International',              region: 'southeast' },
  { code: 'LIT', city: 'Little Rock, AR',         name: 'Bill and Hillary Clinton National',           region: 'south' },
  { code: 'OMA', city: 'Omaha, NE',               name: 'Eppley Airfield',                             region: 'midwest' },
  { code: 'DAL', city: 'Dallas, TX',              name: 'Dallas Love Field',                           region: 'south' },
  { code: 'MEM', city: 'Memphis, TN',             name: 'Memphis International',                       region: 'south' },
  { code: 'ORF', city: 'Norfolk, VA',             name: 'Norfolk International',                       region: 'northeast' },
  { code: 'SYR', city: 'Syracuse, NY',            name: 'Syracuse Hancock International',              region: 'northeast' },
  { code: 'ROC', city: 'Rochester, NY',           name: 'Greater Rochester International',             region: 'northeast' },
  { code: 'MHT', city: 'Manchester, NH',          name: 'Manchester-Boston Regional',                  region: 'northeast' },
  { code: 'PWM', city: 'Portland, ME',            name: 'Portland International Jetport',              region: 'northeast' },
  { code: 'BTV', city: 'Burlington, VT',          name: 'Burlington International',                    region: 'northeast' },
  { code: 'BGR', city: 'Bangor, ME',              name: 'Bangor International',                        region: 'northeast' },
  { code: 'GEG', city: 'Spokane, WA',             name: 'Spokane International',                       region: 'west' },
  { code: 'TUS', city: 'Tucson, AZ',              name: 'Tucson International',                        region: 'mountain' },
  { code: 'ONT', city: 'Ontario, CA',             name: 'Ontario International',                       region: 'west' },
  { code: 'BUR', city: 'Burbank, CA',             name: 'Hollywood Burbank Airport',                   region: 'west' },
  { code: 'FAT', city: 'Fresno, CA',              name: 'Fresno Yosemite International',               region: 'west' },
  { code: 'RNO', city: 'Reno, NV',               name: 'Reno-Tahoe International',                    region: 'mountain' },
  { code: 'COS', city: 'Colorado Springs, CO',    name: 'Colorado Springs Airport',                    region: 'mountain' },
  { code: 'BZN', city: 'Bozeman, MT',             name: 'Bozeman Yellowstone International',           region: 'mountain' },
  { code: 'FAR', city: 'Fargo, ND',               name: 'Hector International',                        region: 'midwest' },
  { code: 'DSM', city: 'Des Moines, IA',          name: 'Des Moines International',                    region: 'midwest' },
  { code: 'FSD', city: 'Sioux Falls, SD',         name: 'Joe Foss Field',                              region: 'midwest' },
]
